# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91bb57ce7e9bd7adc24645405dc0106c112f9548933fce15355491526dd6f613f52f532a7ba54de8bd0807280da9260efa093ec34153ec378a1a88a8a5a6e8d6

test:
  secret_key_base: 1ac6a80c5a28e8c37c3feeeeb0515627fc08d760ab3451156e33174ccb18cc9d3a153c9faaaa5854fa536a5d661aeff89dcba037216a1de2caca7087e2a7a0ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
